### ISSUE TITLE
reload doesn't show content on Chrome on OSX

### ISSUE THREAD

**Issue by mcbrwr** [EightMedia/styleguide.js#12]
When viewing a section in chrome (v44.0.2403.157) on OSX (10.10.5) and reloading the page (cmd-r) the content of the section is not shown. The section is also closed, so maybe the :target selector is not set. 

- When pressing enter in the address bar everything loads as expected
- firefox works fine
- IE 10 works fine

**Comment by Aratramba** [comment]
ok, thanks for the bug report. I don't have much time to fix this and styleguidejs is a little low on my prio list, so might take a while before this gets fixed.

**Comment by mcbrwr** [comment]
I’ll see if I can assist :-)

**Comment by ughitsaaron** [comment]
I'd be happy to take a look as well if some time frees up later this week.

**Comment by Aratramba** [comment]
are you guys still experiencing this issue? It seems to work ok here now (without having touched any code related to this issue)

**Comment by mcbrwr** [comment]
it works.. and I have not updated anything except Chrome.
So it was probably a Chrome bug..
