### ISSUE TITLE
styleguidejs references incompatible version of jade.js with consolidate.js its referencing

### ISSUE THREAD

**Issue by gunalmel** [EightMedia/styleguide.js#7]
consolidate.js got updated recently (first time since 2013) which is incompatible with jade.js ver ~1.1.4 Changing package.json of styleguidejs module to reference jade.js ver ~1.9.1 the error that said "Warning: Object #<Object> has no method 'compileFile' Use --force to continue" when running grunt task has disappeared. You may like to fix that.

**Comment by Aratramba** [comment]
Thanks. Already fixed in 4683ec841e6cc47ca3612f1e7f0511f272c0c6b3. Will be released shortly.

**Comment by Aratramba** [comment]
published 0.1.6 on npm.
