### ISSUE TITLE
commit e3457d9c207 introduced mkdir as a dependency which is missing

### ISSUE THREAD

**Issue by gunalmel** [EightMedia/styleguide.js#8]
e3457d9c2078da699eea0cfc69399e1b45b5b58a requires mkdir but after grunt-styleguidejs is installed it can not be found. It is installed as part of jade dependency but not as part of styleguidjs. Error: Cannot find module 'mkdirp' node_modules/grunt-styleguidejs/node_modules/styleguidejs/lib/index.js:4:14

**Comment by mbaer3000** [comment]
same issue over here: mkdirp ought to be a dependency, as opposed to a devDependency, right?

**Comment by Aratramba** [comment]
sorry, was in a hurry. Does this new release fix it? 7a6f7eaaa71052edf1f61a333b61ef4188961ee0

**Comment by mbaer3000** [comment]
all good now!

**Comment by Aratramba** [comment]
awesome. Thanks for the help!
